# Generated by Django 5.1.4 on 2024-12-15 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_author_product_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_users',
            field=models.ManyToManyField(related_name='like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
